### ISSUE TITLE
Zsh history is not empty

### ISSUE THREAD

**Issue by pistach3** [ShutdownRepo/Exegol#10]
Hi,

Thank you for Exegol, I love it!

I just have a small issue to report: at startup, the zsh history is not empty.

A quick fix is to delete the file `.zsh_history`.

Thanks again for your work ;)

**Comment by ShutdownRepo** [comment]
Thank you @pistach3 ! This is a feature actually. It allows exegol users to look for commands in the history without having to remember syntax, options and such. Personally, I save a lot of time thanks to this. I'll make sure to edit the readme and detail this part.
