### ISSUE TITLE
[Warn] - During an image update

### ISSUE THREAD

**Issue by jenaye** [ShutdownRepo/Exegol#102]
Hello, 
Following the release of exegol 4.0.2 I decided to update the tool and also the AD image

 After 2 hours of downloading I got the following error:

![image](https://user-images.githubusercontent.com/15458329/177501607-e57fd5e6-afc8-4579-929e-36b9f98c2360.png)

when I look at the version, it looks like it went well : 

![image](https://user-images.githubusercontent.com/15458329/177502127-61e66ab4-16fc-4758-8cc9-fcd4f929804e.png)

and when I run the container it works so nothing serious but I wanted to notify the "problem" : 

![image](https://user-images.githubusercontent.com/15458329/177504257-dda2bb75-5249-42f0-90d1-bd08a621f7ab.png)

**Comment by Dramelac** [comment]
I close the ticket because I don't have enough elements to replicate locally.
If the problem persists, don't hesitate to reopen with the debug logs.
