### ISSUE TITLE
[Question] - The version of the main OS can affect the software? 

### ISSUE THREAD

**Issue by jenaye** [ShutdownRepo/Exegol#107]
Pull up, 
Following an internal test, we have tested exegol in its latest version on 2 different physical PCs, 

One under Ubuntu 18.04 and the other under Ubuntu 22.04 and here are the different behaviour 

| Privileged: | On  | Ubuntu 18.04 | Only MDNS | Images : AD/FULL |
|-------------|-----|--------------|-----------|------------------|
| Privileged: | Off | Ubuntu 22.04 | All good  | Images : AD/FULL |
| Privileged: | Off | Ubuntu 18.04 | Only MDNS | Images : AD/FULL |
| Privileged: | On  | Ubuntu 22.04 | All good  | Images : AD/FULL |

I'm not sure if the problem comes from there but in doubt I share the information with you

btw, in this same internal network, we have tested a kali VM in bridge which works correctly having the same version of responder ( 3.1.1.0 ) 

if you have any ideas or suggestions I'd love to hear them

Thank you in advance,

**Comment by jenaye** [comment]
Hello, I am following up on this issue, I have installed ubuntu 18.04 on an x220, exegol is working perfectly as you can see below,

The problem would not come from exegol: 

![image](https://user-images.githubusercontent.com/15458329/181193893-0ddce7b2-46b9-4e63-a46c-b28a5ba2bde7.png)


I would however have a question concerning the resolv.conf, using the default exegol configuration, and in high privilege this file is different between the host and the container, do you have any idea of the reason ? ( once modified like on the host the requests are ok )

Thank you in advance, 
Have a nice day

**Comment by Dramelac** [comment]
Hello,

Indeed Exegol does not seem to be the cause of your problem with responder...

Concerning the resolv.conf, the file is automatically synchronized between the host and the container when the container is started. This synchronization can be "forced" with an `exegol stop <container_name>` followed by an `exegol start <container_name>`.
