### ISSUE TITLE
Feature adding proposition : zshrc

### ISSUE THREAD

**Issue by Rsifff** [ShutdownRepo/Exegol#12]
Hello, thank you for this project, I think it's great. 👍 
You motivated and inspired me to make a configuration deployment script to make a docker with my environment.  🥇 
To thank you, I propose you to use my zsh configuration with its plugins. I think it can bring a plus to Exegol. 
I remain available :
Github : https://github.com/Rsifff/docker/
Twitter : https://twitter.com/Rsifff 
Good continuation.

![screen](https://user-images.githubusercontent.com/66677783/89822182-14bcb700-db50-11ea-9474-f3bb13b73872.png)

**Comment by ShutdownRepo** [comment]
Hey thanks for your contribution! It seems interesting, maybe we could do this :+1: 
Could you describe a bit what each plugin/conf does ? From there we could work on what we keep/edit/...

**Comment by Rsifff** [comment]
Add me on discord : Rsifff#4663
It'll be easier.

**Comment by ShutdownRepo** [comment]
I reviewed you configuration file and kept most of the plugins you had. Thank you for this :ok_hand:
Changes are coming in the next big merge on the master branch but will be available in the following commit on the dev branch
