### ISSUE TITLE
dependencies issue

### ISSUE THREAD

**Issue by onii-sec** [ShutdownRepo/Exegol#124]
```
onii@cat:~$ sudo exegol
Mandatory dependencies are missing: No module named 'rich'
Please install them with pip3 install -r requirements.txt
onii@cat:~$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rich
>>>
```
I also have the right version of rich 
`Requirement already satisfied: rich in ./.local/lib/python3.8/site-packages (11.2.0)`

**Comment by Dramelac** [comment]
Hello,

From what I see, you have installed rich in your user python environment but you run `exegol` in `sudo` so in a root environment which probably doesn't have the dependencies to install.

You can try to run exegol without sudo (see documentation for docker permissions),
or you have to install the python dependencies in the root environment.

**Comment by ShutdownRepo** [comment]
@Dramelac's answer should fix the issue. Closing it
Feel free to open again if needed
