### ISSUE TITLE
Add Mobile pentesting tools

### ISSUE THREAD

**Issue by Fisjkars** [ShutdownRepo/Exegol#17]
Hello, 
First, thanks for the project!
I would like if you are interested to integrate mobile-pentest oriented tools such as apktool, adb, objection, qark etc... in Exegol.
We can imagine to integrate ios and android like you did for proxmark.

I will be glad to contribute on this project, 

Maxime

**Comment by ShutdownRepo** [comment]
Hey :wave: 
Thank you, that would be great, I'm not that experienced with mobile pentest so that'd be awesome to have you onboard!
Let's talk about this on Discord (Shutdown#2539) :wink:

**Comment by Fisjkars** [comment]
Sorry,

I was busy these days, I will add the quick win tool these ween then I will submit a merge request.

**Comment by ShutdownRepo** [comment]
Moving this to the todo list in TODO.md
I'd like to keep issues for issues only
