### ISSUE TITLE
Numpy dependency issue on Windows.

### ISSUE THREAD

**Issue by Fisjkars** [ShutdownRepo/Exegol#33]
Hello,

Thanks again for your project! 

I've noticed a strange behavior today with the master branch inside the exegol.py on Windows.
The requirements.txt file indicate a dependency for pandas 1.0.5. This dependency required numpy >= 1.13.3.

The last version numpy-1.19.4 is not compatible with windows and will display the following message when you tried to use the Python script.

```
The current Numpy installation ('C:\\Users\\XXXX\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```
The solution is to manually downgrade numpy to 1.19.4 with these commands:

```
python -m pip uninstall numpy
pip install numpy==1.19.3
python -m pip install -r requirements.txt
```

I hope this thread could save some time to others users ;)

See ya

**Comment by ShutdownRepo** [comment]
Thank you for this, I'll add your temporary fix to the requirements.txt and will link this thread to the common issues.
