### ISSUE TITLE
THPB2 THPB3 Tools

### ISSUE THREAD

**Issue by jtorrex** [ShutdownRepo/Exegol#36]
Hi @ShutdownRepo

I'm impressed by the project, it have a lot of preinstalled tools that could be very useful for somebody that wants a pentesting enviroment just building a Docker image.

I was thinking on the books The Hacker Playbook 2 and 3, because on the introduction includes a good list for tools related on some diferent hacking topics. (some maybe are old, but some others maybe are useful).

Probably some of the tools are already included on the image, but maybe others no.

Do you think that maybe it's interesting on adding it, or you want to keep a more light image to reduce the overhead on download it?

If you are interested I can look for wich tools are no included and add it on another function like install_thpb_tools, for example.

Give me your opinion, please.

Regards!

**Comment by ShutdownRepo** [comment]
Hey! Thank you for your feedback and for your interest in working with the Exegol team on this :+1: 
I think the smartest thing to do is
1. compare Exegol and THP and identify which tools are missing
2. make sure the missing tools features are really missing and that no other tool already handles those
3. classify the missing tools (web, AD, mobile and so on) and proceed to their installation

Would you be able to do conduct the first step which is basically list the missing tools and comment it in this thread?

**Comment by jtorrex** [comment]
Hello,

I'm busy these days but I've pending to list and check the tools that I proposed before. Probably there are lot of functionalities that are covered but maybe others no.

Give me some time and I try to update the issue during this week.

Regards!

**Comment by ShutdownRepo** [comment]
No rush, we all have busy schedules, thank you for (planning on) contributing :wink:

**Comment by ShutdownRepo** [comment]
Closing this since left unchecked, feel free to open it again
