### ISSUE TITLE
Manque le package python 'censys'

### ISSUE THREAD

**Issue by jdouliez** [ShutdownRepo/Exegol#43]
### PREREQUIS
Installation fraiche de Exegole Stable

### CONTEXTE
Utilisation impossible de l'outil theHarvester

### ANOMALIE
Lors de l'utilisation du programme theHarvester,

```bash
theHarvester -d <DOMAIN> -b all
```
alors  l'erreur suivante apparait 

```
[!] Missing API key for Securitytrail. 
No module named 'censys'
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

### SOLUTION
L'installation du package `censys` résoud le problème

```bash
python3 -m pip install censys
```

**Comment by ShutdownRepo** [comment]
Thank you for this issue :smiley: 
I brought the fix in commit 5bbeea8
The latest commit will soon be merged in the stable (master) branch in version 3.1.6

**Comment by jdouliez** [comment]
Perfect. Thanks ! 👍
