### ISSUE TITLE
John The Ripper not working

### ISSUE THREAD

**Issue by jdouliez** [ShutdownRepo/Exegol#48]
## Issue

Hi,

With a fresh new default container, the program `John The Ripper` is not working.

```
john --fork=4 --format='dynamic=sha512($p.$s)' --wordlist=`fzf-wordlists` hash
zsh: no such file or directory: /opt/tools/john/run/john
```

The `john` alias is set to `/opt/tools/john/run/john`
```
alias | grep john                       
john=/opt/tools/john/run/john
```

But the executable file is not present : 
```
find / -name "john*" -type f 2>/dev/null
/opt/tools/john/run/john.conf
/opt/tools/john/run/john.zsh_completion
/opt/tools/john/run/john.bash_completion
/opt/tools/john/doc/extras/john-1.7.9-jumbo-7-licensing-stats.txt
/opt/tools/john/doc/extras/john-1.7.9-jumbo-7-licensing.txt
/opt/tools/john/src/john.asm
/opt/tools/john/src/john.com
/opt/tools/john/src/johnswap.h
/opt/tools/john/src/john_mpi.c
/opt/tools/john/src/john_mpi.h
/opt/tools/john/src/john.h
/opt/tools/john/src/john_build_rule.h
/opt/tools/john/src/john.c
/usr/share/seclists/Passwords/Software/john-the-ripper.txt
```

Tested on `stable` and `web` images.

## FIX
Installing (the classic way) john from apt fixes the issue.

```
apt install john
unalias john
```

**Comment by TonyRode** [comment]
Hey there,

Thanks for reporting the issue.
I'm testing it aswell, the source code of jtr is already there, but indeed it only needs to be compiled.

Waiting the pull request, a cleaner fix in order to use the source code already present :
```bash
cd /opt/tools/john/src && ./configure && ./make
```
--> It creates the missing `/opt/tools/john/run/john` binary file.

**Comment by ShutdownRepo** [comment]
@TonyRode @jdouliez can you make sure john is working as you'd expect?

**Comment by TonyRode** [comment]
Hey Shutdown,
I've just tested it on a fresh build from master branch right now. It's fixed :)

Didn't try dev one (yet).

**Comment by Tharrisq** [comment]
> Hey Shutdown,
> I've just tested it on a fresh build from master branch right now. It's fixed :)
> 
> Didn't try dev one (yet).

@TonyRode  could you email me please? I have a couple questions for you. tylerwharris62@gmail.com

**Comment by ShutdownRepo** [comment]
@TonyRode awesome, thanks!
I'm closing this since a fixed master implies a fixed dev.
