### ISSUE TITLE
Feature adding proposition : Evil-rm

### ISSUE THREAD

**Issue by en1ma** [ShutdownRepo/Exegol#5]
**Steps to install** 

1) git clone https://github.com/Hackplayers/evil-winrm.git /opt/tools/evil-rm
2) gem install winrm-fs winrm
3) edit your ~/.*rc

done :))

**Comment by ShutdownRepo** [comment]
Thanks for this! Exegol now has evil-winrm since [last commit](https://github.com/ShutdownRepo/Exegol/commit/329759fcafc7d5f5dad8ed68d0114226657d0d26)
