### ISSUE TITLE
Feature adding proposition : redis-tools

### ISSUE THREAD

**Issue by en1ma** [ShutdownRepo/Exegol#7]
**Summary**
redis-tools provides a command line client to interact with redis services(which is sometimes used by servers as a data-structure/database).
[Pentesting Redis service with redis-tools](https://book.hacktricks.xyz/pentesting/6379-pentesting-redis)

**Steps to install**
`sudo apt-get install redis-tools`

**Usage**
```
redis-cli -h <TARGET_IP>
 > info
 > config get *

```

**Comment by ShutdownRepo** [comment]
Thanks for this!
Added it in [this commit](https://github.com/ShutdownRepo/Exegol/commit/709533131ff37a5b281c933b019e4220023d6643).
