### ISSUE TITLE
Mounting current directory

### ISSUE THREAD

**Issue by TH3xACE** [ShutdownRepo/Exegol#75]
Hi,

First of all thank you for this amazing project... I recently started to use it and it is really nice... just wanted to create an issue since it seems that the mounting current directory is not working (exegol start --cwd-mount) or maybe I am not using it as it should ?

**Comment by ShutdownRepo** [comment]
Hey there, thank you 😄 have you taken a look at the `/workspace` directory in the container? That's where the current directory is mounted

**Comment by TH3xACE** [comment]
thanks for replying... didnt find the /workspace directory :(

**Comment by ShutdownRepo** [comment]
Can you please share your command, and the result of your command, running with `-vv` for extra verbosity?
Can you also run `exegol version` on your host, and `cat /opt/.exegol_version` in the container?

**Comment by TH3xACE** [comment]
Command:
 $ exegol start --cwd-mount

 $ exegol version
[*] You are running version 3.1.10

[Jan 31, 2022 - 16:27:34 (UTC)] exegol-master /data # cat /opt/.exegol_version
3.1.10

============================

[DEBUG] Local git branch: master
[+] 1 Exegol images exist
[*] No container tag (-t/--container-tag) supplied
[*] Available local containers: 1
[DEBUG] Fetching details on containers creation
[DEBUG] Looking for the 'DISPLAY' environment variable in the container /exegol-master
[DEBUG] Looking for the 'host' value in the 'Networks' attribute in the container /exegol-master
[DEBUG] Looking for the 'Devices' attribute in the container /exegol-master
[DEBUG] Looking for the 'Privileged' attribute in the container /exegol-master
[DEBUG] Fetching volumes for each container
┌──────────────┬───────────────┬─────────┬────────────────────────┬──────────────────────┬─────────────────────────────────┐
│ Id           │ Container tag │ State   │ Image (repo/image:tag) │ Creation details     │ Binds & mounts                  │
├──────────────┼───────────────┼─────────┼────────────────────────┼──────────────────────┼─────────────────────────────────┤
│ 0b8932a707b0 │ master        │ running │ nwodtuhs/exegol:stable │ --X11 --host-network │ /opt/Exegol/shared-data-volume… │
│              │               │         │                        │                      │ ↔ /data                         │
│              │               │         │                        │                      │ /tmp/.X11-unix ↔ /tmp/.X11-unix │
│              │               │         │                        │                      │ /opt/Exegol/shared-resources ↔  │
│              │               │         │                        │                      │ /opt/resources                  │
│              │               │         │                        │                      │                                 │
└──────────────┴───────────────┴─────────┴────────────────────────┴──────────────────────┴─────────────────────────────────┘

[DEBUG] Available local containers: 1
[DEBUG] Fetching 'FinishedAt' attribute for each container
[DEBUG] └── /exegol-master → 2022-01-28T19:07:04.327440848Z
[DEBUG] Last created container: master
[DEBUG] Fetching volumes for each container
[DEBUG] └── /exegol-master → ['/opt/Exegol/shared-data-volumes/master', '/tmp/.X11-unix', '/opt/Exegol/shared-resources']
[?] What container do you want to start [default: master]? 
[DEBUG] Containers with name exegol-master: 1
[+] Container exists
[+] Container is up
[DEBUG] Looking for the 'Devices' attribute in the container /exegol-master
[DEBUG] Looking for the 'Privileged' attribute in the container /exegol-master
[DEBUG] Looking for the 'host' value in the 'Networks' attribute in the container /exegol-master
[VERBOSE] Container was created with host networking
[DEBUG] Looking for the 'DISPLAY' environment variable in the container /exegol-master
[VERBOSE] Container was created with display sharing
[DEBUG] Looking for the 'DISPLAY' environment variable in the container /exegol-master
[*] Running xhost command for display sharing
[DEBUG] Running command on host with subprocess.Popen(): ['xhost', '+local:exegol-master']
[DEBUG] (cmd stdout) non-network local connections being added to access control list
[*] Entering Exegol
[DEBUG] Running on host with os.system(): docker exec -ti exegol-master zsh

**Comment by TH3xACE** [comment]
It works when creating the container. Ah I see... the mounting can be done only when creating the container ? after creation it cannot be changed ? it stays the same as the one created initially right ?

**Comment by ShutdownRepo** [comment]
You got it 😉 docker works that way 
Closing the issue then

**Comment by TH3xACE** [comment]
Thanks for your help :)
