### ISSUE TITLE
  Feature adding proposition : telnet

### ISSUE THREAD

**Issue by en1ma** [ShutdownRepo/Exegol#8]
**Steps to install**
      apt-get install telnet

**Usage**
https://www.ionos.com/digitalguide/server/tools/telnet-the-system-wide-remote-protocol/

done :))

**Comment by ShutdownRepo** [comment]
Thanks! Added in [this commit](https://github.com/ShutdownRepo/Exegol/commit/4a7689e2bafc36c1543105e3aa416802d003b615)
