### ISSUE TITLE
Printing issue when selecting profile for local build

### ISSUE THREAD

**Issue by ShutdownRepo** [ShutdownRepo/Exegol#84]
When building a local image, the table title is printed with a small UI bug.

![image](https://user-images.githubusercontent.com/40902872/166143980-8b563b6c-be61-4d4e-94e4-966f6c004d9f.png)

I think the issue resides around there
https://github.com/ShutdownRepo/Exegol/blob/1cd921cc997c613a342d4a6f2541261c863259a1/exegol/console/TUI.py#L155-L159

**Comment by Dramelac** [comment]
The problem was the size of the table was too small compared to the size of the title. 
Fixed in the dev branch, will be included in the next release.
