### ISSUE TITLE
 Feature adding proposition : pst-utils 

### ISSUE THREAD

**Issue by en1ma** [ShutdownRepo/Exegol#9]
Tool for reading Microsoft Outlook PST files.

**Steps to install**

apt-get install pst-utils

**Usage**

readpst -S  pstFile.pst

**Comment by ShutdownRepo** [comment]
Thanks! Added in [this commit](https://github.com/ShutdownRepo/Exegol/commit/4a7689e2bafc36c1543105e3aa416802d003b615)
