### ISSUE TITLE
nmap issue on Mac M1 (pcap_create(eth0) FAILED:)

### ISSUE THREAD

**Issue by elektron14** [ShutdownRepo/Exegol#91]
Hello guys ! 
First of all, thanks a lot for your great job !

I would like to submit an issue that I faced with nmap on Mac M1. I don't know if I am the only one having this issue related to pcap ?

➜  Exegol exegol start
[*] Exegol is currently in version v4.0.1
[*] Starting exegol                                                                                                                                                                                                   

👽 Available containers                                         
┌───────────────┬─────────┬───────────┬────────────────────────┐
│ Container tag │ State   │ Image tag │ Configurations         │
├───────────────┼─────────┼───────────┼────────────────────────┤
│ test          │ Running │ nightly   │ Privileged: On 🔥      │
│               │         │           │ GUI: Off 🪓            │
│               │         │           │ Share timezone: Off 🪓 │
└───────────────┴─────────┴───────────┴────────────────────────┘

[*] You can use a name that does not already exist to create a new container                                                                                                                                          
[?] Select a container by its name (test): 
[*] Location of the exegol workspace on the host : /Users/adrien/.exegol/workspaces/test                                                                                                                              
[+] Opening shell in Exegol 'test'                                                                                                                                                                                    
[May 19, 2022 - 22:42:00 (CEST)] exegol-test /workspace # nmap -sS -n --open -p 88 192.168.1.0/24 
Starting Nmap 7.92 ( https://nmap.org ) at 2022-05-19 22:42 CEST
pcap_create(eth0) FAILED: eth0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: Function not implemented.
Call to pcap_open_live() failed three times. There are several possible reasons for this, depending on your operating system:
LINUX: If you are getting Socket type not supported, try modprobe af_packet or recompile your kernel with PACKET enabled.
 *BSD:  If you are getting device not configured, you need to recompile your kernel with Berkeley Packet Filter support.  If you are getting No such file or directory, try creating the device (eg cd /dev; MAKEDEV <device>; or use mknod).
*WINDOWS:  Nmap only supports ethernet interfaces on Windows for most operations because Microsoft disabled raw sockets as of Windows XP SP2.  Depending on the reason for this error, it is possible that the --unprivileged command-line argument will help.
SOLARIS:  If you are trying to scan localhost or the address of an interface and are getting '/dev/lo0: No such file or directory' or 'lo0: No DLPI device found', complain to Sun.  I don't think Solaris can support advanced localhost scans.  You can probably use "-Pn -sT localhost" though.

QUITTING!

Maybe other Mac users have solved the issue ? 

Thanks, 
BR

**Comment by ShutdownRepo** [comment]
Hello there :wave: I'm closing this issue since it's a duplicate to https://github.com/ShutdownRepo/Exegol-images/issues/9
Exegol images are not multi architectures yet. Creating a linux/arm64 will solve it, we're on it.
