### ISSUE TITLE
Sudo / Python long start

### ISSUE THREAD

**Issue by lap1nou** [ShutdownRepo/Exegol#99]
Hello,

I think I found a bug in the Docker image, I'm not sure but Python scripts that requires `sudo` take a long time to run, for example the brute force utility `patator` or the Python 3 module `http.server` used to spawn a fast web server.

I think the root cause is that sudo try to resolve the machine hostname (no idea why), here is a screen when I run `sudo` in Exegol (which is useless since we are root):
![image](https://user-images.githubusercontent.com/10383569/171053236-ab91680d-f736-46de-ab1d-09d7d37fb742.png)

However If I add the hostname of my container in the `/etc/hosts` file:
![image](https://user-images.githubusercontent.com/10383569/171053296-fe30330a-94a6-48ac-a1d2-cad4fed0bf04.png)

All 'long' command, become instantaneous, I have no idea why `patator` works better with this, since it doesn't have any links with `sudo`, same for `http.server` (except if you use port below 1024 ofc). I'm sorry if you don't encounter the same bug as me, or if this bug is fixed already (I got the last version of Exegol 4.0.2), anyway the potential fix would be the add the hostname during the build of the container, here is a post talking about this: https://stackoverflow.com/questions/38302867/how-to-update-etc-hosts-file-in-docker-image-during-docker-build, a possible solution would be to use the `--add-host` arguments during build, but I never tested it, I could potentially try to work on the problem if other people have the same issue as me.

(Now that I think about it, this issue is maybe more related to Exegol itself, tell me what you think)

Anyway thank you for Exegol.

**Comment by Dramelac** [comment]
Adding exegol hostname dynamically to `/etc/hosts` as extra-host via python wrapper 
Changed in dev branch with commit 1304b21c3528e0aa0ae57d4c2c909efbdf8305d1
Will be release with 4.0.3
